### ISSUE TITLE
gatsby-theme-stitches plugin update

### ISSUE THREAD

**Issue by cometkim** [desktopofsamuel/juxtdesign-blog#3]
Hey, thank for using [gatsby-theme-stitches](https://github.com/cometkim/gatsby-theme-stitches).

I found that SSR at v0.1.0 was not working properly, so fixed it in v0.1.1.

please upgrade the plugin to get proper initial render performance!

**Comment by desktopofsamuel** [comment]
@cometkim Thanks a lot for the notification. Fixed in the latest update already!  https://github.com/desktopofsamuel/juxtdesign-blog/commit/0e1b9fed1c8dc8d41d59dc6731a1de1657f692a6
